# Generated by Django 5.1.2 on 2024-10-11 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sujeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('fotografia', models.ImageField(upload_to='sujetos/fotos/')),
                ('estado_salud', models.TextField(blank=True)),
                ('tarjeta_control_sanitario', models.BooleanField(default=False)),
                ('tarjeta_numero', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField()),
                ('fecha_multa', models.DateField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False)),
                ('detalles_articulo', models.TextField()),
                ('sujeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_medico.sujeto')),
            ],
        ),
        migrations.CreateModel(
            name='InspeccionSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateField()),
                ('resultado_inspeccion', models.TextField()),
                ('testigos', models.TextField()),
                ('inspector', models.CharField(max_length=255)),
                ('sujeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_medico.sujeto')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('aviso_funcionamiento', models.BooleanField(default=False)),
                ('sujeto_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_medico.sujeto')),
            ],
        ),
    ]
