# Generated by Django 5.1.2 on 2024-11-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_medico', '0002_contact_event_file_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(choices=[('general', 'Médica General'), ('nutricional', 'Nutricional'), ('psicologica', 'Psicológica')], max_length=20)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('recomendaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado_salud', models.TextField(blank=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='control_medico.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='control_medico.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='control_medico.paciente'),
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=255)),
                ('dosis', models.CharField(max_length=100)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('fecha_prescripcion', models.DateField(auto_now_add=True)),
                ('historial_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='control_medico.historialmedico')),
            ],
        ),
    ]
