# Generated by Django 5.1.2 on 2024-11-01 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_medico', '0003_consulta_paciente_historialmedico_consulta_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
