# Generated by Django 5.1.2 on 2024-11-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_medico', '0005_centronocturno_sexoservidora_inspector_multatarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sexoservidora',
            name='apellidos_materno',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sexoservidora',
            name='apellidos_paterno',
            field=models.CharField(default='', max_length=255),
        ),
    ]
